
INSERT INTO {table_prefix}soconfig VALUES

(null,"{store_id}","soconfig_custom_store","{\"cssinput_status\":\"0\",\"cssinput_content\":\"\",\"cssfile_status\":\"0\",\"cssfile_url\":[\"catalog\\/view\\/theme\\/so-revo\\/css\\/custom.css\"],\"jsinput_status\":\"0\",\"jsinput_content\":\"\"}","1"),
(null,"{store_id}","soconfig_social_store","{\"social_sidebar\":\"1\",\"social_fb_status\":\"1\",\"facebook\":\"magentech\",\"social_twitter_status\":\"1\",\"twitter\":\"smartaddons\",\"social_custom_status\":\"1\",\"video_code\":{\"2\":\"&lt;h3&gt;&lt;span style=&quot;font-size: 18px;&quot;&gt;Guide Create Social Wickgets&amp;nbsp;&lt;\\/span&gt;&lt;\\/h3&gt;&lt;span style=&quot;font-size: 18px;&quot;&gt;\\r\\n&lt;\\/span&gt;&lt;p&gt;You please login admin, then select\\r\\n&lt;span style=&quot;font-weight: bold;&quot;&gt;&amp;nbsp;Extension tab &amp;gt; Modules &amp;gt; Theme Control Panel &amp;gt; Tab Social Wickgets:&lt;\\/span&gt;\\r\\nPlease enter data content&lt;\\/p&gt;\",\"1\":\"&lt;h3&gt;&lt;span style=&quot;font-size: 18px;&quot;&gt;Guide Create Social Wickgets&amp;nbsp;&lt;\\/span&gt;&lt;\\/h3&gt;&lt;span style=&quot;font-size: 18px;&quot;&gt;\\r\\n&lt;\\/span&gt;&lt;p&gt;You please login admin, then select\\r\\n&lt;span style=&quot;font-weight: bold;&quot;&gt;&amp;nbsp;Extension tab &amp;gt; Modules &amp;gt; Theme Control Panel &amp;gt; Tab Social Wickgets:&lt;\\/span&gt;\\r\\nPlease enter data content&lt;\\/p&gt;\"}}","1"),
(null,"{store_id}","soconfig_fonts_store","{\"body_status\":\"google\",\"normal_body\":\"Arial, Helvetica, sans-serif\",\"url_body\":\"https:\\/\\/fonts.googleapis.com\\/css?family=Roboto:300,400,700\",\"family_body\":\"\'Roboto\', sans-serif\",\"selector_body\":\"body\",\"menu_status\":\"standard\",\"normal_menu\":\"inherit\",\"url_menu\":\"\",\"family_menu\":\"\",\"selector_menu\":\"\",\"heading_status\":\"standard\",\"normal_heading\":\"inherit\",\"url_heading\":\"\",\"family_heading\":\"\",\"selector_heading\":\"\"}","1"),
(null,"{store_id}","soconfig_layout_store","{\"layoutstyle\":\"full\",\"theme_bgcolor\":\"#7a167a\",\"pattern\":\"6\",\"contentbg\":\"\",\"content_bg_mode\":\"repeat\",\"content_attachment\":\"scroll\"}","1"),
(null,"{store_id}","soconfig_pages_store","{\"catalog_col_position\":\"outside\",\"catalog_col_type\":\"default\",\"catalog_sidebar_sticky\":\"disable\",\"product_catalog_refine\":\"1\",\"catalog_refine_number\":\"5\",\"lstimg_cate_status\":\"1\",\"product_catalog_mode\":\"grid-4\",\"discount_status\":\"1\",\"countdown_status\":\"1\",\"rating_status\":\"1\",\"product_order\":\"1\",\"card_gallery\":\"2\",\"placeholder_status\":\"1\",\"placeholder_img\":\"catalog\\/logo2.png\",\"desktop_addcart_position\":\"center\",\"quick_status\":\"1\",\"desktop_addcart_status\":\"1\",\"desktop_wishlist_status\":\"1\",\"desktop_Compare_status\":\"1\",\"radio_style\":\"1\",\"thumbnails_position\":\"bottom\",\"product_enablezoom\":\"1\",\"product_enablesizechart\":\"0\",\"tabs_position\":\"2\",\"product_enableshowmore\":\"1\",\"product_enableshipping\":\"0\",\"product_contentshipping\":{\"2\":\"Custom block Html\",\"1\":\"Custom block Html\"},\"product_page_button\":\"1\",\"product_socialshare\":{\"2\":\"Custom block Html\",\"1\":\"Custom block Html\"},\"related_status\":\"1\",\"product_related_column_lg\":\"3\",\"product_related_column_md\":\"2\",\"product_related_column_sm\":\"2\",\"product_related_column_xs\":\"1\",\"comingsoon_imglogo\":\"catalog\\/logo2.png\",\"comingsoon_title\":{\"2\":\"Coming Soon Title\",\"1\":\"Coming Soon Title\"},\"comingsoon_date\":\"2018-05-26\",\"comingsoon_content\":{\"2\":\"Coming soon content\",\"1\":\"Coming soon content\"}}","1"),
(null,"{store_id}","soconfig_general_store","{\"typelayout\":\"2\",\"themecolor\":\"orange\",\"toppanel_status\":\"0\",\"toppanel_type\":\"1\",\"phone_status\":\"1\",\"contact_number\":{\"2\":\"&lt;div class=&quot;contact-us&quot;&gt;&lt;i class=&quot;fa fa-volume-control-phone&quot;&gt;&lt;\\/i&gt;&lt;span class=&quot;text&quot;&gt;Hotline: &lt;\\/span&gt;&lt;span &gt; +123 456 7890&lt;\\/span&gt;&lt;\\/div&gt;\",\"1\":\"&lt;div class=&quot;contact-us&quot;&gt;&lt;i class=&quot;fa fa-volume-control-phone&quot;&gt;&lt;\\/i&gt;&lt;span class=&quot;text&quot;&gt;Hotline: &lt;\\/span&gt;&lt;span &gt; +123 456 7890&lt;\\/span&gt;&lt;\\/div&gt;\"},\"welcome_message_status\":\"0\",\"welcome_message\":{\"2\":\"Welcome Message Arabic\",\"1\":\"Welcome Message English\"},\"checkout_status\":\"0\",\"lang_status\":\"1\",\"preloader\":\"1\",\"preloader_animation\":\"line\",\"imgpayment_status\":\"0\",\"imgpayment\":\"catalog\\/demo\\/payment\\/payment.png\",\"copyright\":\"Designed by &lt;a href=&quot;http:\\/\\/www.opencartworks.com\\/&quot; target=&quot;_blank&quot;&gt;OpenCartWorks.Com&lt;\\/a&gt;\",\"typeheader\":\"2\",\"typefooter\":\"2\",\"type_banner\":\"4\",\"img_sizechart\":\"\"}","1"),
(null,"{store_id}","soconfig_advanced_store","{\"name_color\":\"orange\",\"theme_color\":\"#Fd6500\",\"scsscompile\":\"0\",\"scssformat\":\"Nested\",\"compileMutiColor\":\"0\",\"cssminify\":\"0\",\"cssExclude\":[{\"namecss\":\"catalog\\/view\\/javascript\\/font-awesome\\/css\\/font-awesome.min.css\"}],\"jsminify\":\"0\",\"jsExclude\":[{\"namecss\":\"catalog\\/view\\/javascript\\/jquery\\/datetimepicker\\/moment\\/moment-with-locales.min.js\"}]}","1");
